### ISSUE TITLE
Test, document, and review modified code

### ISSUE THREAD

**Issue by steve-crouch** [Southampton-RSG-Training/dirac-test-document-review-old#1]
Testing Strategy and planning [Alpha]
Development tools IDE's and debuggers [Alpha]
Reviewing Code []
Documentation [Alpha]

**Comment by PipGrylls** [comment]
Testing Strategy and planning, @jag1g13 2 days effort, review @PipGrylls 
Development tools IDE's and debuggers, @steve-crouch 4 days effort, review @smangham 
Reviewing Code, @steve-crouch 1 day effort, review @jag1g13

**Comment by steve-crouch** [comment]
Completed.
